// This file was generated by basehub. Do not edit directly. Read more: https://basehub.com/docs/api-reference/basehub-sdk

/* eslint-disable */
/* eslint-disable eslint-comments/no-restricted-disable */
/* tslint:disable */
// @ts-nocheck

import * as React from "react";
import { PumpProps } from "./server-pump";
import type { PumpState } from "./types";
import { ResolvedRef } from "../../common-types";
export declare const ClientPump: <Queries extends PumpQuery[]>({ children, rawQueries, pumpEndpoint, pumpToken: initialPumpToken, initialState, initialResolvedChildren, apiVersion, resolvedRef, }: {
    children: PumpProps<Queries>["children"];
    rawQueries: Array<{
        query: string;
        variables?: any;
    }>;
    pumpEndpoint: string;
    pumpToken: string | undefined;
    initialState: PumpState | undefined;
    initialResolvedChildren?: React.ReactNode;
    apiVersion: string;
    resolvedRef: ResolvedRef;
}) => import("react/jsx-runtime").JSX.Element;
