// This file was generated by basehub. Do not edit directly. Read more: https://basehub.com/docs/api-reference/basehub-sdk

/* eslint-disable */
/* eslint-disable eslint-comments/no-restricted-disable */
/* tslint:disable */
// @ts-nocheck

export declare const ServerToolbar: ({ ...basehubProps }: any) => Promise<import("react/jsx-runtime").JSX.Element>;
